# config/packages/doctrine_mongodb.yaml
doctrine_mongodb:
  connections:
    default:
      server: "%env(MONGODB_URL)%"

  default_database: "%env(MONGODB_DB)%"

  document_managers:
    default:
      auto_mapping: true
