doctrine_mongodb:
  connections:
    default:
      server: "%env(MONGODB_URL)%"
      options: {}
  default_database: "%env(MONGODB_DB)%"
  document_managers:
    default:
      auto_mapping: true
      mappings:
        App:
          is_bundle: false
          type: attribute # Assurez-vous que vous utilisez bien les attributs PHP 8.1+ pour vos documents
          dir: "%kernel.project_dir%/src/Document"
          prefix: 'App\Document'
          alias: App
